name: CI

on:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '!benchmark/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/compiled_python.yml'
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '!benchmark/**'
      - '.github/workflows/ci.yml'
      - '.github/workflows/compiled_python.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read  # to fetch code (actions/checkout)


jobs:
  ci:
    env:
      OS_NAME: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      COVERAGE: false
      GCC_VERSION: 9
      USE_CCACHE: 1
      CCACHE_SLOPPINESS: "pch_defines,time_macros"
      CCACHE_COMPRESS: 1
      CCACHE_MAXSIZE: "100M"
      LXML_CSTD: c11

    strategy:
      # Allows for matrix sub-jobs to fail without canceling the rest
      fail-fast: false

      # MATRIX:
      # =======
      # Required parameters:
      #  os                  the os to run on
      #  python-version      the python version to use
      #  env                 any additional env variables. Set to '{}' for none
      # Optional parameters:
      #  allowed_failure     whether the job is allowed to fail
      #  extra_hash          extra hash str to differentiate from other caches with similar name (must always start with '-')
      matrix:
        os:
          - "ubuntu-22.04"
          - "ubuntu-22.04-arm"
          - "macos-latest"
          - "windows-2022"
          - "windows-11-arm"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.13t"
          - "3.14"
          - "3.14t"
          - "3.15-dev"
          - "3.15t-dev"
        env:
          - {}

        include:
          - os: ubuntu-latest
            python-version: "3.9"
            env: {WITH_REFNANNY: true}
            extra_hash: "-refnanny"
          - os: ubuntu-latest
            python-version: "3.13"
            env: {WITH_REFNANNY: true}
            extra_hash: "-refnanny"

          # Coverage setup
          - os: ubuntu-latest
            python-version: "3.10"
            env: { COVERAGE: true }
            extra_hash: "-coverage"
          - os: ubuntu-latest
            python-version: "3.10"
            env: { EXTRA_DEPS: "docutils pygments sphinx sphinx_book_theme" }
            extra_hash: "-docs"

          # Ubuntu sub-jobs: Pypy
          - os: ubuntu-latest
            python-version: pypy-3.9
            env: {}
            allowed_failure: true
          - os: ubuntu-latest
            python-version: pypy-3.10
            env: {}
            allowed_failure: true
          - os: ubuntu-latest
            python-version: pypy-3.11
            env: {}
            allowed_failure: true

        exclude:
          - os: windows-11-arm
            python-version: "3.9"  # setup-python only supports 3.11+ on windows arm
          - os: windows-11-arm
            python-version: "3.10"  # setup-python only supports 3.11+ on windows arm

    # This defaults to 360 minutes (6h) which is way too long and if a test gets stuck, it can block other pipelines.
    # From testing, the runs tend to take 8-20 minutes, so a limit of 45 minutes should be enough.
    timeout-minutes: 45

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install MacOS dependencies
        if: runner.os == 'macOS'
        run: |
          brew install automake libtool ccache
          ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize

      - name: ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # v1.2.23
        if: runner.os == 'Linux' || runner.os == 'macOS'
        with:
          max-size: 100M
          create-symlink: true
          key: ${{ runner.os }}-${{ runner.arch }}-ccache${{ matrix.extra_hash }}-${{ matrix.python-version }}

      - name: Run CI
        continue-on-error: ${{ matrix.allowed_failure || false }}
        env: ${{ matrix.env }}
        run: bash -c 'GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}"  bash ./tools/ci-run.sh'

      - name: Build docs
        if: contains( matrix.env.EXTRA_DEPS, 'sphinx')
        run: make html

      - name: Upload docs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.extra_hash == '-docs'
        with:
          name: website_html
          path: doc/html
          if-no-files-found: ignore

      - name: Upload Coverage Report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: matrix.env.COVERAGE
        with:
          name: pycoverage_html
          path: coverage*
          if-no-files-found: ignore

  pydebug:
    uses: ./.github/workflows/compiled_python.yml
    with:
      name: pydebug
      freethreading: false
    secrets: inherit

  pydebug-ft:
    uses: ./.github/workflows/compiled_python.yml
    with:
      name: pydebug
      freethreading: true
    secrets: inherit
